services:
  app:
    build:
      context: .
    container_name: palworld-wine
    env_file:
      - ./.env
    ports:
      - 8211:8211/udp # Required UDP game Port
      - 25575:25575 # Optional RDP port
      - 27015:27015 # Optional Query port
    volumes:
      - ./app:/app # Where Steamcmd and Palworld is going to live
      - ./app/backup:/backup # Palworld Backup Locations
      - ./mods:/mods
    restart: unless-stopped

