name: Docker Image CI palworld-wine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Checkout Github Actions
      uses: actions/checkout@main

    - name: Login to GHCR
      uses: docker/login-action@main
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GHCR_TOKEN}}
    
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/ripps818/palworld-wine:latest
        docker push ghcr.io/ripps818/palworld-wine:latest
